language: python
python:
  - "3.3"
install:
    - pip install nose
    - pip install lxml
    - pip install pypdf2
    - pip install jinja2
    - pip install cherrypy
    - pip install coveralls
script: nosetests --with-coverage --cover-package=aquarius
after_success: coveralls